package com.whereisdarran.kybrid.model

enum class Callback {
    CONNECT_SUCCESS,
    CONNECT_FAILURE,
    SEND_SUCCESS,
    SEND_FAILURE,
    ON_DATA_CALLBACK,
    ON_CONNECT_CALLBACK,
    ON_CLOSE_CALLBACK,
    DISCONNECT_SUCCESS,
    DISCONNECT_FAILURE,
    LISTEN_SUCCESS,
    LISTEN_FAILURE,
    GET_ADDRESS_SUCCESS,
    GET_ADDRESS_FAILURE
}